### ISSUE TITLE
`job_type = check` is fully broken since #565: `main()` reads `alg.res_dir` on a `ModelCheck`, which is not an `Algorithm`

### ISSUE THREAD

**Issue by wshlavacek** [lanl/PyBNF#569]
Every `job_type = check` run on current `main` (095a5a14..b8c05769) dies in setup, before the model is ever evaluated:

```
Sorry, an unknown error occurred: AttributeError: 'ModelCheck' object has no attribute 'res_dir'
```

```
Traceback (most recent call last):
  File "pybnf/pybnf.py", line 667, in main
    alg.method_chain = method_chain.chain_for_run(alg.res_dir, config.config,
                                                  ^^^^^^^^^^^
AttributeError: 'ModelCheck' object has no attribute 'res_dir'
```

The failure is in setup, not in the reporting tail, so a check job now produces **no objective value at all**. It is not degraded output; the fit type does not start.

## Where it happens

`pybnf/pybnf.py:664-690`, introduced by 0750b687 (#565):

```python
        # The record of which methods this run actually executes (#564/ADR-0107). Kept
        # on the algorithm beside the budget, and written after every phase, so it is
        # complete on disk even if a later phase raises.
        alg.method_chain = method_chain.chain_for_run(alg.res_dir, config.config,   # <- line 667
                                                      budget=alg.budget, version=__version__)

        ...

        if config.config['fit_type'] != 'check':                                    # <- line 676
            # Set up cluster
            cluster = Cluster(config, log_prefix, debug, cmdline_args.log_level)
            ...
        else:
            # Run model checking
            logger.debug('Model checking initialization')
            alg.run_check(debug=debug)

        fit_status, fit_reason = _phase_status(alg)                                 # <- line 687
        _record_phase(alg, 'fit', config.config['fit_type'], fit_status, reason=fit_reason,
                      simulations=alg.completed_simulations,
                      best_objective=alg.trajectory.best_score() if len(alg.trajectory) else None)
```

Line 667 runs unconditionally. Line 676, nine lines later, is the branch that exists precisely because the check path is not an algorithm run. The check path therefore reaches 667 first and dies there.

`ModelCheck` deliberately does not subclass `Algorithm` — its own docstring says so, and `pybnf.py`'s branch is the consequence — so it has none of the attributes the new lines read:

```
>>> alg = ModelCheck(config)
>>> [hasattr(alg, a) for a in ('res_dir', 'stop_reason', 'completed_simulations', 'trajectory')]
[False, False, False, False]
```

**Line 667 is not the only break.** Guarding it alone moves the crash nine lines down: `_phase_status(alg)` at 687 reads `alg.stop_reason`, and `_record_phase` at 688-690 reads `alg.completed_simulations` and `alg.trajectory`. All three are `Algorithm` surface and all three are missing on `ModelCheck`. Both sites have to move inside the branch for the check path to run at all.

A third, cosmetic consequence: because the run fails, `_finalize` calls `alg.cleanup()` on the cleanup path and logs a second `AttributeError` ('ModelCheck' object has no attribute 'cleanup'). That one is swallowed by design and is not worth chasing separately — it disappears once the run stops failing.

### `alg.budget` is fine, and for a stated reason

`alg.budget = FitBudget.from_config(...)` at line 646 also runs unconditionally, but it does not have the same problem: assigning an attribute to a `ModelCheck` instance is legal, and `Configuration._strip_uncheckable_keys` pops `wall_time_fit` before defaults are applied —

```python
        for k in ('refine', 'bootstrap', 'wall_time_fit'):
            conf_dict.pop(k, None)
```

— so `from_config` sees a limit of 0 and returns `None`. The budget block below it is skipped and no misleading "Wall-time budget for this fit" line is printed for a job that has no run to budget. That is deliberate, documented behaviour ("a check is one evaluation of given parameters, not a search"), not an accident. The same strip is why `_refine_best_fit` and `_run_bootstrapping` further down still no-op safely on the check path.

## Why it was not caught

`job_type = check` has tests — `tests/test_model_check.py`, `tests/full_tests/T6-check/` — but every one of them calls `run_check()` directly, and `run_check()` is not what broke. Nothing drives `main()`'s check path, so two commits (35a2dc04, b8c05769) landed on top of a fit type that could not start.

## Reproducer

Any edition-2 check config. The original report used an SBML model with all parameters baked in and a `fix_at` sigma:

```
job_type = check
sbml_backend = bngsim
edition = 2
model: model.xml
noise_model = lognormal, sigma = fix_at 0.065
observable: Ca, formula: Z_state*1.0 + 0.22
experiment: experiment1, method: ode, data: experiment1.exp
```

It reproduces with no simulator at all, which is what makes it cheap to regression-test — an analytical menu target scored through `objective = score`:

```
edition = 2
model = g.target : target.exp
output_dir = out
objective = score
job_type = check
```

with `g.target` = `{"type": "gaussian", "mean": [], "variance": []}` and a one-row `target.exp`. On b8c05769 this exits 1 with the traceback above; it should print `Objective value is 0.0`.

## The fix

Move the method-chain construction and the fit-phase recording inside the `fit_type != 'check'` branch, where the rest of the `Algorithm`-only sequence already lives, and say in a comment why the boundary is there so the next addition to `main()` lands on the correct side of it.

A check run has no method chain by design: it is one evaluation of the parameters as given, not a chain of search phases, and `ModelCheck` has no `Results` directory of its own to write the record into. (`_prepare_run_directories` does create `output_dir/Results` for every run, so giving `check` a one-phase record is *possible* — but `phases`, `simulations`, `best_objective` and `stop_reason` would all be empty or invented, and #564's point was provenance a consumer can rely on. Not worth it here.)

Plus the regression test that is missing: run a `job_type = check` job end to end through `main()` and assert it exits 0 and reports its objective value.
